<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.superiormc.enchantmentreform</groupId>
        <artifactId>EnchantmentReform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>plugin</artifactId>
    <packaging>jar</packaging>

    <build>
        <finalName>${name}-${revision}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.1</version>
                <configuration>
                    <forceCreation>true</forceCreation>
                    <archive>
                        <manifestEntries>
                            <paperweight-mappings-namespace>spigot</paperweight-mappings-namespace>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/MANIFEST.MF</exclude>
                                <exclude>module-info.class</exclude>
                                <exclude>META-INF/versions/*/module-info.class</exclude>
                            </excludes>
                        </filter>
                    </filters>
                    <relocations>
                        <relocation>
                            <pattern>redempt.crunch</pattern>
                            <shadedPattern>cn.superiormc.enchantmentreform.libs.crunch</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>cn.gtemc.itembridge</pattern>
                            <shadedPattern>cn.superiormc.enchantmentreform.libs.itembridge</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.bstats</pattern>
                            <shadedPattern>cn.superiormc.enchantmentreform.bstats</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>nms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>nms-advice-1_21_11</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>nms-advice-26_1</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>spigot</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.superiormc.enchantmentreform</groupId>
            <artifactId>paper</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
